-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCR23iWsYaOxhTky4
4nF1/efURwlLwDyXLgkwEvQ1FN+gCgYIKoZIzj0DAQehRANCAAT8xtcijUE3nZVd
6Jk5M1PIjQmHpo6yt9coEf/qCVQHtQeGHsLT/em6Gj3UlYCm1NI7lnZG+9oMWJNl
ifThAmx6
-----END PRIVATE KEY-----